#!/bin/sh
set -e

case "$1" in
    configure)
        udevadm control --reload-rules || true
        udevadm trigger || true

        if ! getent group gameperf > /dev/null; then
            groupadd -r gameperf
        fi

        systemctl daemon-reload || true
        systemctl enable --now gameperf-daemon.service || true
        ;;
esac

#DEBHELPER#

exit 0
