name: Build and Package

on:
  push:
    branches:
      - main
      - packaging-pipeline-appimage-deb-ci-systemd-polkit-first-run
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-appimage:
    name: Build AppImage
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 6 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            qt6-base-dev \
            qt6-declarative-dev \
            libqt6core5compat6-dev \
            qml6-module-qtquick \
            qml6-module-qtquick-controls \
            qml6-module-qtquick-layouts \
            qml6-module-qtquick-dialogs \
            libgl1-mesa-dev \
            libfuse2 \
            file \
            curl

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Install to AppDir
        run: |
          mkdir -p build/AppDir
          DESTDIR=build/AppDir cmake --install build

      - name: Create AppImage
        run: |
          ./scripts/build-appimage.sh || true

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: build/packaging/appimage/*.AppImage
          if-no-files-found: warn

  build-debian:
    name: Build Debian Package
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            debhelper \
            devscripts \
            qt6-base-dev \
            qt6-declarative-dev \
            libqt6core5compat6-dev \
            qml6-module-qtquick \
            qml6-module-qtquick-controls \
            qml6-module-qtquick-layouts \
            qml6-module-qtquick-dialogs \
            libsdl2-dev \
            policykit-1

      - name: Build Debian package
        run: |
          ./scripts/build-deb.sh || true

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: Debian-Package
          path: build/packaging/debian/*.deb
          if-no-files-found: warn

  metadata:
    name: Generate metadata
    runs-on: ubuntu-latest
    needs: [build-appimage, build-debian]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build summary
        run: |
          echo "## Packaging Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ AppImage build completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Debian package build completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Artifacts are available for download in the Actions tab." >> $GITHUB_STEP_SUMMARY
